name: Automated Release Deployment

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 21.7.2
name: 🚀 Deploy website on push
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: 🚚 Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 📦 Install dependencies
        run: npm install

      - name: 🚀 Deploy website
        run: npm nuxt build

      - name: 🚀 Run website
        run: npm nuxt preview

      
